config/routes.rb
Rails.application.routes.draw do
  resources :articles, :except => [:show, :delete]

  delete 'articles/:id', to: 'articles#destroy', as: :delete_article
  get 'articles/:id', to: 'articles#show', as: :article_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class='container'>
  <%= form_for @article do |f| %>
  <div class='form-field'>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Article title' %>
  </div>
  <div class='form-field'>
    <%= f.label :content %>
    <%= f.text_field :content, placeholder: 'Your article here..' %>
  </div>
  <div class='form-field'>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form', articles: @article %>

app/views/articles/index.html.erb
<div class='container'>
  <% @articles.each do |article| %>
    <div class='container-small'>
      <h3> <%= link_to article.title, article_show_path(article.id) %></h3>
      <p><%= article.content %></p>
    </div>
  <% end %>
</div>
<div class='container'>
  <%= link_to 'Add article', new_article_path %>
</div>

app/views/articles/new.html.erb
<%= render 'form', articles: @article %>

app/views/articles/show.html.erb
<div>
  <h3 class=in-line><%= @article.title %></h3>
  <%= link_to '🖋', edit_article_path(@article.id) %>
  <%= link_to '🗑️', article_path(@article), method: :delete, data: { confirm: 'Are you sure you want to destroy this piece of art, leaving mankind a little less knowledgeable?'} %>
</div>
<div>
  <p class=in-line><%= @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Wikinimous</h1>
    <%= yield %>
  </body>
</html>